ViewModels/BikeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Sjx_Mvc.ViewModels
{
    public class BikeViewModel
    {
       
        [Required]

        [Display(Name = "Rider Name")]
        public string RidersName { get; set; }

        [Required]
        [Display(Name = "Bike Number")]
        public DateTime CreatedAt { get; set; } 
        public DateTime DueDate { get; set; } 
        public string BikeNo { get; set; }
        public string Registration { get; set; }
        [Required]
        public string dateofpurchase { get; set; }
        [Required]
        public string colour { get; set; }



    }
}

Controllers/BikeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Sjx_Mvc.Models;
using Sjx_Mvc.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Sjx_Mvc.Controllers
{
    public class BikeController : Controller
    {


        [HttpGet]
      public IActionResult CreateBike()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> CreateBike(BikeViewModel model)
        {
            string successMessage = "Bike Assigned to Rider Successfully ";
            BikeViewModel bikeModel = new BikeViewModel();
            if (ModelState.IsValid)
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");
                string url = "https://sjx-logistics-api.herokuapp.com/api/Bikes/bike";
                using (var httpClient = new HttpClient())
                {

                    using (var response = await httpClient.PostAsync(url, content))
                    {
                        if (response.IsSuccessStatusCode)
                        {

                            string apiResponse = await response.Content.ReadAsStringAsync();
                            bikeModel = JsonConvert.DeserializeObject<BikeViewModel>(apiResponse);
                            TempData["successMessage"] = successMessage;
                            ModelState.Clear();
                            model.RidersName= "";
                            model.BikeNo = "";

                        }
                        else
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            Response<BikeViewModel> resp = JsonConvert.DeserializeObject<Response<BikeViewModel>>(apiResponse);
                            TempData["errorMessage"] = resp.Messages;
                            ModelState.Clear();
                            model.RidersName = "";
                            model.BikeNo = "";
                        }

                    }
                  
                }
            }

            return View(model);



        }


        [HttpGet]

        public async Task<IActionResult> GetBikes()
        {

            Response<IEnumerable<BikeViewModel>> bikes = null;
            string url = "https://sjx-logistics-api.herokuapp.com/api/Bikes/getBikes";


            using (var httpClient = new HttpClient())
            {

                using (var response = await httpClient.GetAsync(url))
                {
                    if (response.IsSuccessStatusCode)
                    {

                        string apiResponse = await response.Content.ReadAsStringAsync();
                        bikes = JsonConvert.DeserializeObject<Response<IEnumerable<BikeViewModel>>>(apiResponse);


                    }
                    else
                    {
                        throw new Exception(response.ReasonPhrase);
                    }
                    return View(bikes.Data);
                }
            }
        }


    }
}

Views/Bike/CreateBike.cshtml
@model Sjx_Mvc.ViewModels.BikeViewModel

@{
    ViewBag.Title = "Create Bike";
}


<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Coronation Corporate Portal | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="~/asset/css/style.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/asset/css/style.css" rel="stylesheet" />
</head>
<body class=" ">
    <div class="row">
        <div class="col-md-12 bgimg ">
            <div>
                <div class="login-box">
                    <div class="login-logo">
                    </div>
                    <div class="card">
                        <div class="card-body login-card-body">
                            <div class="card-header">
                                <h4 class="card-title text-center" style="margin-left:2rem">Create bike</h4>
                            </div>
                            @if (TempData["successMessage"] != null)
                            {
                                <div class="alert alert-success alert-dismissible fade show" role="alert">
                                    <span style="font-size: 15px">@TempData["successMessage"]</span>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                            }
                            @if (TempData["errorMessage"] != null)
                            {
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    <span style="font-size: 15px">@TempData["errorMessage"]</span>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            }

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <form asp-action="CreateBike" asp-controller="Bike" method="post">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <input asp-for="RidersName" class="form-control" placeholder="Rider Name" />
                                    </div>
                                    <div class="input-group mb-3">

                                        <span asp-validation-for="RidersName" class="text-danger mx-auto"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <input asp-for="BikeNo" class="form-control" placeholder="Bike no" />
                                    </div>
                                    <div class="input-group mb-3">

                                        <span asp-validation-for="BikeNo" class="text-danger mx-auto"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <input asp-for="Registration" class="form-control" placeholder="Plate no" />
                                    </div>
                                    <div class="input-group mb-3">

                                        <span asp-validation-for="Registration" class="text-danger mx-auto"></span>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <input asp-for="dateofpurchase" class="form-control" placeholder="Purchase date" />
                                        </div>
                                        <div class="input-group mb-3">

                                            <span asp-validation-for="dateofpurchase" class="text-danger mx-auto"></span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <input asp-for="colour" class="form-control" placeholder="Colour" />
                                        </div>
                                        <div class="input-group mb-3">

                                            <span asp-validation-for="colour" class="text-danger mx-auto"></span>
                                        </div>
                                    </div>

                                </div>

                                <div class="form-group push-up-20">
                                    <div class="mx-auto">
                                        <input type="submit" value="Submit" class="btn btn-primary btn-block" />
                                    </div>

                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
  
    @*<script src="~/plugins/jquery/jquery.min.js"></script>*@
    <script src="~/lib/jquery/jquery.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>


</body>
</html>





Views/Bike/GetBikes.cshtml
@model IEnumerable<Sjx_Mvc.ViewModels.BikeViewModel>
@{
    ViewData["Title"] = "Bike List";
}


<link href="~/css/site.css" rel="stylesheet" />
<h1 class="text-center">Bikes</h1>



<section class="content">
    <div style="margin-left: 16rem">
    <div class="row">
        <div class="col-12">


            <div class="card">
                <div class="card-header">

                </div>
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped responsive-table">
                        <thead>
                            <tr>
                                <th>S/N</th>
                                <th>Bike Number</th>
                                <th>Rider Name</th>
                                <th>Registration</th>
                                <th>Date Of Purchase</th>
                                <th>Colour</th>
                                <th>Created Date</th>
                                <th>Date of Maintenance</th>
                            </tr>

                        </thead>
                        <tbody id="quotesRow">

                            @if (Model.Count() == 0)
                            {
                                <tr>
                                    <td colspan="7" class="text-center">No Record Found</td>
                                </tr>
                            }
                            else

                            {
                                int count = 0;
                                foreach (var user in Model)

                                {
                                  count++;

                        <tr class="odd gradeX">
                            <td style="width:5%">@count</td>
                            <td style="width:15%">@user.BikeNo</td>
                            <td style="width:10%">@user.RidersName </td>
                            <td style="width:10%">@user.Registration</td>
                            <td style="width:20%">@user.dateofpurchase </td>
                            <td style="width:10%">@user.colour </td>
                            <td style="width:30%">@user.CreatedAt</td>
                            <td style="width:45%">@user.DueDate</td>
                            <td>
                            </td>
                        </tr>
                            }
                            }

                            </tbody>

                        </table>
                    @*asp-route-Email="@user.Email.ToString()"*@


                    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>*@

                    @*<script src="~/plugins/popper/popper.js"></script>
                        <script src="~/plugins/popper/popper-utils.js"></script>*@
                    <script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
                    <script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>

                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
        </div>
    <!-- /.row -->
</section>





<script>
    //$(document).ready(function () {
    //    $("body").tooltip({ selector: '[data-toggle=tooltip]' });
    //});
    $(function () {
        $("#example").dataTable();
    })
    $(function () {
        $("#example1").DataTable({
            "responsive": true,
            "autoWidth": false,
        });
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });


    $(document).ready(function () {
        $('#searchTerm').keydown(function () {
            var searchTerm = $(this).val();
            var url = 'Account/GetAllUsers?searchTerm='

            $.ajax({
                type: "Post",
                url: url + searchTerm,
                contentType: "html",
                success: function (response) {
                    $("#quotesRow").html(response);
                }
            })
        })

    })

    @*function exported(e) {
        debugger
        $.ajax({
            type: "POST",
            url: '@Url.Action("ExportListUsingEPPlus", "Account")', //call your controller and action
            contentType: "application/json; charset=utf-8",
            dataType: "json",
        }).done(function (data) {

            //get the file name for download
            if (data.fileName != "") {
                //use window.location.href for redirect to download action for download the file

                window.location.href = "@Url.RouteUrl(new { Controller = "Account", Action = "Download" })/?fileName=" + data.fileName;

            }
        });*@
    }
</script>

